% generatePlotsPooledKernels.m
%
% Script to load analyzed data (from extractKernels.m) and generate plots
%  with plotMeanKernels.m. Saves figures
%
% UPDATED: 8/29/19
%

datPath = '/Users/hyang/Dropbox (HMS)/2PAnalysis-Helen/AnalyzedData/190828';
figPath = '/Users/hyang/Dropbox (HMS)/2PAnalysis-Helen/Figures/190828_kernels';

allCellTypes = {'a01', 'a02', 'b05', 'b06', 'g13', 'g14', 'g15', 'g16', ...
    'g31', 'g34', 'p05', 'p09', 'p11', 'p12', 'p18', 'p32'};

yScale = {[-4e-4 16e-4]...
    [-1e-5 2e-5]...
    [-1e-3 2e-3]...
    [-1e-5 4e-5]...
    [-0.5e-5 2.5e-5]...
    [-0.15 0.4]...
    [-20 20]...
    [-0.3 0.3]...
    [-2 10]...
    [-5 20]};

yLabels = {'dF/F unit per mm/s',...
    'dF/F unit per deg/s', ...
    'dF/F unit per mm/s', ...
    'dF/F unit per deg/s', ...
    'dF/F unit per deg/s', ...
    'mm/s per unit dF/F', ...
    'deg/s per unit dF/F', ...
    'mm/s per unit dF/F', ...
    'deg/s per unit dF/F', ...
    'deg/s per unit dF/F'};

degPerMM = 17.738631428198860;

yScaleAllDeg = {[-3e-5 9e-5]...
    [-1e-5 2e-5]...
    [-6e-5 10e-5]...
    [-1e-5 4e-5]...
    [-0.5e-5 2.5e-5]...
    [-3 10]...
    [-20 20]...
    [-5 5]...
    [-2 10]...
    [-5 20]};

yLabelsAllDeg = {'dF/F unit per deg/s',...
    'dF/F unit per deg/s', ...
    'dF/F unit per deg/s', ...
    'dF/F unit per deg/s', ...
    'dF/F unit per deg/s', ...
    'deg/s per unit dF/F', ...
    'deg/s per unit dF/F', ...
    'deg/s per unit dF/F', ...
    'deg/s per unit dF/F', ...
    'deg/s per unit dF/F'};

for i = 1:length(yScaleAllDeg)
    yScaleAllDegSEM{i} = yScaleAllDeg{i} * 1.5;
end

cd (datPath)

for i = 1:length(allCellTypes)
    load([allCellTypes{i} '.mat'], 'kernels', 'kernelParams');
    
f = plotMeanKernels(kernels, kernelParams, yScaleAllDeg, allCellTypes{i}, ...
    yLabelsAllDeg, degPerMM, 0, 0, 0);
    

end