% plotAllKernelPred.m
%
% Function to plot all kernels, variance explained scatterplots, and
%  measured vs. predicted responses for all kernels when given kernels
%  struct and the corresponding kernelParams and kernelResampInputs structs
%  generated by extractAllKernels().
% Calls plot1KernelPred()
% NOTE: for a fly where both the left and right cells are included, this
%  generates 24 separate figures
% 
% INPUTS:
%   kernels - kernels struct from extractAllKernels()
%   kernelParams - kernels parameter struct from extractAllKernels()
%   kernelResampInputs - kernels inputs, resampled at kernel time scale,
%       from extractAllKernels()
% OUTPUTS:
%   none, but produces figures
%
% CREATED: 5/24/19
% UPDATED: 5/24/19
%

function plotAllKernelPred(kernels, kernelParams, kernelResampInputs)
    

end
